version: "3"

services:
  node-server:
    build: 
      context: ./node-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3008:8080"

  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3060"
    environment:
      - NODE_ENV=development

  server-nuxt2:
    build: 
      context: ./nuxt-2
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3020:3000"

  server-nuxt3:
    build: 
      context: ./nuxt-3
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3030:3000"

