version: "3"

services:
  node-server:
    image: everjupe13/itmo_research_work-node_server:latest
    restart: always
    ports:
      - "8080:8080"

  web:
    image: everjupe13/itmo_research_work-frontend:latest
    restart: always
    ports:
      - "3000:3060"
    environment:
      - NODE_ENV=development

  server-nuxt2:
    image: everjupe13/itmo_research_work-nuxt2:latest
    restart: always
    ports:
      - "3020:3000"

  server-nuxt3:
    image: everjupe13/itmo_research_work-nuxt3:latest
    restart: always
    ports:
      - "3030:3000"

