name: This Workflow Runs On Pushing

on:
  push:
    branches:
      - master

jobs:
  nuxt3-tests:
    name: Nuxt 3 TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.18.0"

      - name: Install JavaScript dependencies
        with:
          node-version: "18.18.0"

      - name: Run JavaScript Linters
        run: |
          cd nuxt-3
          yarn
          yarn run lint

  nuxt2-tests:
    name: Nuxt 2 TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.18.0"

      - name: Install JavaScript dependencies
        with:
          node-version: "18.18.0"

      - name: Run JavaScript Linters
        run: |
          cd nuxt-2
          yarn
          yarn run lint

  node-server-tests:
    name: Node server TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.0"

      - name: Install dependencies & Run TypeScript Linters
        run: |
          cd node-server
          yarn
          yarn run lint

  frontend-tests:
    name: Frontend TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.19.0"

      - name: Install dependencies & Run TypeScript Linters
        run: |
          cd frontend
          yarn
          yarn run lint
