name: This Workflow Runs On Pushing

on:
  push:
    branches:
      - master

jobs:
  nuxt3-tests:
    name: Nuxt 3 TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.18.0"

      - name: Install Nuxt 3 dependencies & Run Linters
        run: |
          cd nuxt-3
          yarn
          yarn run lint

  nuxt2-tests:
    name: Nuxt 2 TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.18.0"

      - name: Install Nuxt 2 dependencies & Run Linters
        run: |
          cd nuxt-2
          yarn
          yarn run lint

  node-server-tests:
    name: Node server TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.0"

      - name: Install dependencies & Run TypeScript Linters
        run: |
          cd node-server
          yarn
          yarn run lint

  frontend-tests:
    name: Frontend TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.19.0"

      - name: Install dependencies & Run TypeScript Linters
        run: |
          cd frontend
          yarn
          yarn run lint

  build_and_push_to_docker_hub:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    needs: [nuxt2-tests, nuxt3-tests, node-server-tests, frontend-tests]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Nuxt 2 Docker image
        uses: docker/build-push-action@v2
        with:
          context: nuxt-2/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/itmo_research_work-nuxt2:latest

      - name: Build and push Nuxt 3 Docker image
        uses: docker/build-push-action@v2
        with:
          context: nuxt-3/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/itmo_research_work-nuxt3:latest

      - name: Build and push Node Server Docker image
        uses: docker/build-push-action@v2
        with:
          context: node-server/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/itmo_research_work-node_server:latest

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: frontend/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/itmo_research_work-frontend:latest

      # - name: Build and push Terms Glossary Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: terms_glossary/
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/itmo_research_work-terms_glossary:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: Update docker-compose.yaml on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            curl -sSL "https://raw.githubusercontent.com/everjupe13/itmo-research-experiment-3/master/docker-compose.yml" | cat > /home/itmo/itmo-research-experiment-3/docker-compose.yaml
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/itmo/itmo-research-experiment-3
            sudo docker pull everjupe13/itmo_research_work-node_server:latest
            sudo docker pull everjupe13/itmo_research_work-frontend:latest
            sudo docker pull everjupe13/itmo_research_work-nuxt2:latest
            sudo docker pull everjupe13/itmo_research_work-nuxt3:latest
            sudo docker-compose down -v
            sudo docker-compose up -d
